## 1# Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.2.1+cu121


## Creating Tensors

In [3]:
## Scalers

s1 = torch.tensor(10)
print(s1)

tensor(10)


In [4]:
s1.ndim

0

In [5]:
## Get number back as Python int
s1.item()

10

In [6]:
## Vector

v1 = torch.tensor([5, 5])
v1

tensor([5, 5])

In [7]:
v1.ndim

1

In [8]:
v1.shape

torch.Size([2])

In [9]:
## Matrix
M1 = torch.tensor([[7,8],
                   [9,10]])

M1

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
M1.ndim

2

In [11]:
M1[1]

tensor([ 9, 10])

In [12]:
M1.shape

torch.Size([2, 2])

In [13]:
## Tensor
T1 = torch.tensor([[[1,2,3],
                    [3,6,9],
                    [2,5,8]]])
T1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 8]]])

In [14]:
T1.ndim

3

In [15]:
T1.shape

torch.Size([1, 3, 3])

In [16]:
T1[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 8]])

# 2# Creating Random Tensors in PyTorch




In [17]:
randTensor1 = torch.rand(3,4)
randTensor1

tensor([[0.9444, 0.1367, 0.7238, 0.6188],
        [0.8842, 0.5379, 0.1217, 0.1745],
        [0.7306, 0.2234, 0.9167, 0.9247]])

In [18]:
randTensor1.ndim

2

In [19]:
randTensor2 = torch.rand(1,3,3)
randTensor2

tensor([[[0.5402, 0.1250, 0.7241],
         [0.8934, 0.4068, 0.3555],
         [0.0219, 0.7632, 0.1264]]])

In [20]:
randTensor2.ndim

3

In [21]:
## Create a random tensor similar to image shape

image_tensor = torch.rand(size=(512,512,3))
image_tensor
image_tensor.shape, image_tensor.ndim

(torch.Size([512, 512, 3]), 3)

# Creating Tensors With Zeros and Ones in PyTorch

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros([3,4])
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * randTensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all Ones

ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
## Default datatype of pytorch tensor
ones.dtype

torch.float32

In [26]:
randTensor1.dtype

torch.float32

# Creating a Tensor Range and Tensors Like Other Tensors

In [27]:
## Use tourch.arange

one_to_zero = torch.arange(start=0, end=10)
one_to_zero

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
## Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_zero)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Dealing With Tensor Data Types

In [29]:
# Float 32-bit Tensor
float_32_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=None)

float_32_tensor

tensor([3., 5., 7.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=torch.float16)

float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [32]:
float_32_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=False)

float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 25., 49.])

In [35]:
int_32_tensor = torch.tensor([3, 5, 7], dtype=torch.int32)
int_32_tensor

tensor([3, 5, 7], dtype=torch.int32)

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 25., 49.])

In [37]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

# Getting information from tensors
1. Tensors not right datatype - to get datatypes from tensor, can use `tensor.dtype`.
2. Tensors not right shape - to get shape a tensor, can use `tensor.shape`.
3. Tensor not on the right device - to get devices from a tensor, can use `tensor.device`.

In [41]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.0048, 0.0811, 0.3641, 0.3178],
        [0.1787, 0.6045, 0.2611, 0.4315],
        [0.0921, 0.0505, 0.5911, 0.9893]])

In [42]:
print(rand_tensor)
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Device tensor is on: {rand_tensor.device}")

tensor([[0.0048, 0.0811, 0.3641, 0.3178],
        [0.1787, 0.6045, 0.2611, 0.4315],
        [0.0921, 0.0505, 0.5911, 0.9893]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
