## 1# Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.2.1+cu121


## Creating Tensors

In [ ]:
## Scalers

s1 = torch.tensor(10)
print(s1)

tensor(10)


In [ ]:
s1.ndim

0

In [ ]:
## Get number back as Python int
s1.item()

10

In [ ]:
## Vector

v1 = torch.tensor([5, 5])
v1

tensor([5, 5])

In [ ]:
v1.ndim

1

In [ ]:
v1.shape

torch.Size([2])

In [ ]:
## Matrix
M1 = torch.tensor([[7,8],
                   [9,10]])

M1

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
M1.ndim

2

In [ ]:
M1[1]

tensor([ 9, 10])

In [ ]:
M1.shape

torch.Size([2, 2])

In [ ]:
## Tensor
T1 = torch.tensor([[[1,2,3],
                    [3,6,9],
                    [2,5,8]]])
T1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 8]]])

In [ ]:
T1.ndim

3

In [ ]:
T1.shape

torch.Size([1, 3, 3])

In [ ]:
T1[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 8]])

# 2# Creating Random Tensors in PyTorch




In [ ]:
randTensor1 = torch.rand(3,4)
randTensor1

tensor([[0.1451, 0.2902, 0.8625, 0.2323],
        [0.1560, 0.1644, 0.1213, 0.4316],
        [0.4202, 0.8006, 0.4501, 0.0207]])

In [ ]:
randTensor1.ndim

2

In [ ]:
randTensor2 = torch.rand(1,3,3)
randTensor2

tensor([[[0.2066, 0.5904, 0.7620],
         [0.3598, 0.8179, 0.1525],
         [0.2068, 0.6249, 0.1393]]])

In [ ]:
randTensor2.ndim

3

In [ ]:
## Create a random tensor similar to image shape

image_tensor = torch.rand(size=(512,512,3))
image_tensor
image_tensor.shape, image_tensor.ndim

(torch.Size([512, 512, 3]), 3)

# Creating Tensors With Zeros and Ones in PyTorch

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros([3,4])
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * randTensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all Ones

ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
## Default datatype of pytorch tensor
ones.dtype

torch.float32

In [ ]:
randTensor1.dtype

torch.float32

# Creating a Tensor Range and Tensors Like Other Tensors

In [ ]:
## Use tourch.arange

one_to_zero = torch.arange(start=0, end=10)
one_to_zero

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_zero)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Dealing With Tensor Data Types

In [ ]:
# Float 32-bit Tensor
float_32_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=None)

float_32_tensor

tensor([3., 5., 7.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=torch.float16)

float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [ ]:
float_32_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=False)

float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 25., 49.])

In [ ]:
int_32_tensor = torch.tensor([3, 5, 7], dtype=torch.int32)
int_32_tensor

tensor([3, 5, 7], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 25., 49.])

In [ ]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

# Getting information from tensors
1. Tensors not right datatype - to get datatypes from tensor, can use `tensor.dtype`.
2. Tensors not right shape - to get shape a tensor, can use `tensor.shape`.
3. Tensor not on the right device - to get devices from a tensor, can use `tensor.device`.

In [ ]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.2450, 0.0439, 0.6533, 0.6983],
        [0.8119, 0.2215, 0.6241, 0.3484],
        [0.5524, 0.5265, 0.3085, 0.2475]])

In [ ]:
print(rand_tensor)
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Device tensor is on: {rand_tensor.device}")

tensor([[0.2450, 0.0439, 0.6533, 0.6983],
        [0.8119, 0.2215, 0.6241, 0.3484],
        [0.5524, 0.5265, 0.3085, 0.2475]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Math Operations with Tensors

**Tensor operations include:**
- Addition
- Subtraction
- Multiplication (Element-wise)
- Division
- Matrix Multiplication

In [ ]:
#Create a tensor
tensor = torch.tensor([10, 20, 30])
tensor

tensor([10, 20, 30])

In [ ]:
#Addition
print(tensor + 10)
print(torch.add(tensor, 20))

tensor([20, 30, 40])
tensor([30, 40, 50])


In [ ]:
#Multiplication
print(tensor * 10)
print(torch.mul(tensor, 10))

tensor([100, 200, 300])
tensor([100, 200, 300])


In [ ]:
print(tensor/2)
print(torch.divide(tensor, 2))

tensor([ 5., 10., 15.])
tensor([ 5., 10., 15.])
