## 1# Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.2.1+cu121


## Creating Tensors

In [3]:
## Scalers

s1 = torch.tensor(10)
print(s1)

tensor(10)


In [4]:
s1.ndim

0

In [5]:
## Get number back as Python int
s1.item()

10

In [6]:
## Vector

v1 = torch.tensor([5, 5])
v1

tensor([5, 5])

In [7]:
v1.ndim

1

In [8]:
v1.shape

torch.Size([2])

In [9]:
## Matrix
M1 = torch.tensor([[7,8],
                   [9,10]])

M1

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
M1.ndim

2

In [11]:
M1[1]

tensor([ 9, 10])

In [12]:
M1.shape

torch.Size([2, 2])

In [13]:
## Tensor
T1 = torch.tensor([[[1,2,3],
                    [3,6,9],
                    [2,5,8]]])
T1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 8]]])

In [14]:
T1.ndim

3

In [15]:
T1.shape

torch.Size([1, 3, 3])

In [16]:
T1[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 8]])

# 2# Creating Random Tensors in PyTorch




In [17]:
randTensor1 = torch.rand(3,4)
randTensor1

tensor([[0.3541, 0.7916, 0.9834, 0.9832],
        [0.8685, 0.2084, 0.0152, 0.8382],
        [0.9359, 0.9075, 0.4938, 0.4972]])

In [18]:
randTensor1.ndim

2

In [19]:
randTensor2 = torch.rand(1,3,3)
randTensor2

tensor([[[0.6276, 0.3743, 0.5012],
         [0.8509, 0.1763, 0.3496],
         [0.4578, 0.0196, 0.8915]]])

In [20]:
randTensor2.ndim

3

In [21]:
## Create a random tensor similar to image shape

image_tensor = torch.rand(size=(512,512,3))
image_tensor
image_tensor.shape, image_tensor.ndim

(torch.Size([512, 512, 3]), 3)

# Creating Tensors With Zeros and Ones in PyTorch

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros([3,4])
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * randTensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all Ones

ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
## Default datatype of pytorch tensor
ones.dtype

torch.float32

In [26]:
randTensor1.dtype

torch.float32

# Creating a Tensor Range and Tensors Like Other Tensors

In [27]:
## Use tourch.arange

one_to_zero = torch.arange(start=0, end=10)
one_to_zero

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
## Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_zero)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Dealing With Tensor Data Types

In [29]:
# Float 32-bit Tensor
float_32_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=None)

float_32_tensor

tensor([3., 5., 7.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=torch.float16)

float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [32]:
float_32_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=False)

float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 25., 49.])

In [35]:
int_32_tensor = torch.tensor([3, 5, 7], dtype=torch.int32)
int_32_tensor

tensor([3, 5, 7], dtype=torch.int32)

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 25., 49.])

In [37]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

# Getting information from tensors
1. Tensors not right datatype - to get datatypes from tensor, can use `tensor.dtype`.
2. Tensors not right shape - to get shape a tensor, can use `tensor.shape`.
3. Tensor not on the right device - to get devices from a tensor, can use `tensor.device`.

In [38]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.0470, 0.3736, 0.5526, 0.1468],
        [0.6771, 0.8303, 0.3584, 0.2032],
        [0.4455, 0.9581, 0.7517, 0.4102]])

In [39]:
print(rand_tensor)
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Device tensor is on: {rand_tensor.device}")

tensor([[0.0470, 0.3736, 0.5526, 0.1468],
        [0.6771, 0.8303, 0.3584, 0.2032],
        [0.4455, 0.9581, 0.7517, 0.4102]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Math Operations with Tensors

**Tensor operations include:**
- Addition
- Subtraction
- Multiplication (Element-wise)
- Division
- Matrix Multiplication

In [40]:
#Create a tensor
tensor = torch.tensor([10, 20, 30])
tensor

tensor([10, 20, 30])

In [41]:
#Addition
print(tensor + 10)
print(torch.add(tensor, 20))

tensor([20, 30, 40])
tensor([30, 40, 50])


In [42]:
#Multiplication
print(tensor * 10)
print(torch.mul(tensor, 10))

tensor([100, 200, 300])
tensor([100, 200, 300])


In [43]:
print(tensor/2)
print(torch.divide(tensor, 2))

tensor([ 5., 10., 15.])
tensor([ 5., 10., 15.])


# Matrix Multiplication

Matrix multiplication is a fundamental operation in linear algebra that involves multiplying two matrices to produce a new matrix. In order for matrix multiplication to be defined, the number of columns in the first matrix must be equal to the number of rows in the second matrix.

Given two matrices:

$A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{bmatrix}$

and

$B = \begin{bmatrix} b_{11} & b_{12} & \cdots & b_{1p} \\ b_{21} & b_{22} & \cdots & b_{2p} \\ \vdots & \vdots & \ddots & \vdots \\ b_{n1} & b_{n2} & \cdots & b_{np} \end{bmatrix}$

the product of matrices $( A )$ and $( B )$ (denoted as $( AB ))$ is calculated as follows:

$AB = \begin{bmatrix} c_{11} & c_{12} & \cdots & c_{1p} \\ c_{21} & c_{22} & \cdots & c_{2p} \\ \vdots & \vdots & \ddots & \vdots \\ c_{m1} & c_{m2} & \cdots & c_{mp} \end{bmatrix}$

where each element $( c_{ij} )$ of the resulting matrix $( C )$ is obtained by taking the dot product of the $( i )$-th row of matrix $( A )$ and the $( j )$-th column of matrix $( B )$:

$c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + \cdots + a_{in}b_{nj} = \sum_{k=1}^{n} a_{ik}b_{kj}$

Matrix multiplication can be performed using different methods, such as the row-by-column method, where each element of the resulting matrix is computed individually, or more efficient algorithms like the Strassen algorithm or the Coppersmith–Winograd algorithm, which are used for large matrices.

Matrix multiplication is used in various fields such as computer graphics, robotics, physics, and engineering for solving systems of linear equations, transformations, and many other applications.

Two main ways of performing multiplication in neural networks and deep learning:

### 1. Element-wise multiplicaion

![Alt text](https://www.mathsisfun.com/algebra/images/matrix-multiply-constant.svg "a title")

### 2. Matrix multiplication (dot product)

![Alt text](https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg "a title")

In [44]:
#Import Pytorch
import torch

In [45]:
#Element wise multiplication
tensor = torch.tensor([10, 20, 30])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [46]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(1400)

In [47]:
tensor

tensor([10, 20, 30])

In [48]:
# #let's do it by hand
10*10 + 20*20 + 30*30

1400

In [49]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(1400)
CPU times: user 2.16 ms, sys: 0 ns, total: 2.16 ms
Wall time: 3.57 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.23 ms, sys: 0 ns, total: 1.23 ms
Wall time: 1.15 ms


tensor(1400)

# Matrix Multiplication PART-2
## Two main ways of performing multiplication in neural networks and deep learning:

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(4, 3) @ (4, 3)` won't work
* `(3, 4) @ (4, 3)` will work
* `(4, 3) @ (3, 4)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(3, 4) @ (4, 3)` -> `(3, 3)`
* `(4, 3) @ (3, 4)` -> `(4, 4)`

In [51]:
mat1 = torch.rand(4,3)
print(mat1)

tensor([[0.9466, 0.9981, 0.6670],
        [0.0774, 0.9455, 0.3516],
        [0.0309, 0.7610, 0.0465],
        [0.8770, 0.1508, 0.8680]])


In [52]:
mat2 = torch.rand(3,4)
print(mat2)

tensor([[0.2689, 0.0745, 0.7951, 0.7135],
        [0.0928, 0.1324, 0.1802, 0.8671],
        [0.2622, 0.0775, 0.3442, 0.4048]])


In [53]:
torch.matmul(mat1,mat2)

tensor([[0.5221, 0.2543, 1.1621, 1.8110],
        [0.2007, 0.1581, 0.3530, 1.0174],
        [0.0911, 0.1066, 0.1777, 0.7008],
        [0.4774, 0.1525, 1.0232, 1.1079]])

# Matrix Multiplication PART-3
## Dealing with matrix shape errors

In [55]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [58]:
 tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [60]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [61]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])